### ISSUE TITLE
Payfort module

### ISSUE THREAD

**Issue by jesydeepu** [payfort/prestashop#4]
Hii, I just installed payfort module.Uploaded via filezilla to 'modules' section in my server . But it's not showing up in back office modules  in prestashop . PHP installed on development/production servers ihave an evssl certificate and support TLS 1.2. OpenSSL/1.0.2e
i'm using php 7 
prestashop version 1.6.1.4 
but what might be causing the issue?

**Comment by alovak** [comment]
hi @jesydeepu 

can you please send us email at start [ at ] payfort.com?

we need temporary ftp credentials to find why it's so. But please don't put them here ;) just send them in email.

**Comment by jesydeepu** [comment]
Sorry Sir. Its working now. I forgot to change the filter contents in
search box, which resulted in not showing the module.
& extremely thankful for your support.
